package ua.epam.travelagencyms.controller.actions.constants;

public class Parameters {
    public static final String ID = "id";
    public static final String ACTION = "action";
    public static final String LOCALE = "locale";
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String ERROR = "error";
    public static final String MESSAGE = "message";
    public static final String USER = "user";
    public static final String TOUR = "tour";
    public static final String CURRENT_PATH = "currentPath";
    public static final String CONFIRM_PASSWORD = "confirm-password";
    public static final String PROFILE_PAGE = "profile.jsp";
    public static final String AUTHENTIFICATION_CODE = "authcode";
    public static final String LOGGED_USER = "loggedUser";
    public static final String ROLE = "role";
    public static final String NAME = "name";
    public static final String SURNAME = "surname";
    public static final String RECORDS = "records";
    public static final String OFFSET = "offset";
    public static final String CURRENT_PAGE = "currentPage";
    public static final String START = "start";
    public static final String END = "end";
    public static final String PAGES = "pages";
    public static final String OLD_PASSWORD = "old-password";
    public static final String USERS = "users";
    public static final String TOURS = "tours";
    public static final String SORT = "sort";
    public static final String ORDER_STATUS_ID = "status";
    public static final String ORDER = "order";
    public static final String USER_ID = "user-id";
    public static final String TOUR_ID = "tour-id";
    public static final String AVATAR = "avatar";
    public static final String ORDER_ID = "order-id";
    public static final String STATUS = "status";

    public static final String TITLE = "title";
    public static final String PERSONS = "persons";
    public static final String ORDERS = "orders";
    public static final String MIN_PRICE = "min_price";
    public static final String MAX_PRICE = "max_price";
    public static final String PRICE = "price";
    public static final String HOT = "hot";
    public static final String DISCOUNT = "discount";
    public static final String TOUR_PRICE = "tour-price";
    public static final String TYPE = "type";
    public static final String HOTEL = "hotel";
    public static final String IMAGE = "image";
}
